server:
  port: 8000

spring:
  application:
    name: gateway-service
  config:
    import:
      - classpath:gateway-routes.yml
      - classpath:gateway-filter.yml
      - classpath:gateway-cors.yml

  cloud:
    nacos:
      discovery:
        server-addr: "[::1]:8848"
        username: nacos
        password: nacos

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
