server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      serverAddr: "[::1]:8848"
      # 以下配置项必须填写
      username: "nacos"
      password: "nacos"
    gateway:
      discovery:
        locator:
          enabled: true # 开启服务发现自动路由
          lower-case-service-id: true # 可选，服务名转小写
