spring:
  application:
    name: ai-service
  ai:
    openai:
      # api-key:
      # deepseek
      # api-key:
      # base-url: https://api.openai.com/v1/
      base-url: https://api.deepseek.com
      chat:
        options:
          # 模型名称。deepseek-chat指向V3模型，deepseek-reasoner指向R1模型
          model: deepseek-chat
          # 多样性系数。常值在0.1-0.9之间，数值越大，生成的内容越多样化，推荐设置0.7
          temperature: 0.7
        enabled: true
