spring:
  application:
    name: user-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://mysql-primary:3306/user_db
    username: myuser
    password: ENC(WDYgHWcc1tNPwrX5vHV/bLhMOjokAensnK9nUnUKup8UGsL41zjjbfTpBFHaaqBJ)
    driver-class-name: com.mysql.cj.jdbc.Driver

  docker:
    compose:
      enabled: false

server:
  port: 9000
  # profiles:
  #   active: dev

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:okrm@2025}
