server:
  port: 9000

spring:
  profiles:
    active: dev
  application:
    name: user-service
  config:
    import:
      - nacos:security.yml?refreshEnabled=true&group=DEFAULT_GROUP
  cloud:
    nacos:
      serverAddr: "[::1]:8848"
      # 以下配置项必须填写
      username: "nacos"
      password: "nacos"
      discovery:
        server-addr: 127.0.0.1:8848
        # namespace: DEFAULT_NAMESPACE
        service: ${spring.application.name}
        group: DEFAULT_GROUP
        enabled: true
        register-enabled: true
        username: "nacos"
        password: "nacos"
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        "[use_sql_comments]": true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          "[time_zone]": UTC
    # database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    # url: jdbc:mysql://mysql-primary:3306/user_db
    url: jdbc:mysql://localhost:3306/user_db
    username: myuser
    password: ENC(WDYgHWcc1tNPwrX5vHV/bLhMOjokAensnK9nUnUKup8UGsL41zjjbfTpBFHaaqBJ)
    driver-class-name: com.mysql.cj.jdbc.Driver

  docker:
    compose:
      enabled: false

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:okrm@2025}

logging:
  file:
    path: ${user.home}/.okrm/logs/user-service
  level:
    root: INFO
    org:
      springframework:
        orm:
          jpa: DEBUG
      hibernate: DEBUG
    com:
      "[useful_person]":
        okrm: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
