server:
  port: 9000
  profiles:
    active: dev

spring:
  application:
    name: user-service

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC
    # database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://mysql-primary:3306/user_db
    username: myuser
    password: ENC(WDYgHWcc1tNPwrX5vHV/bLhMOjokAensnK9nUnUKup8UGsL41zjjbfTpBFHaaqBJ)
    driver-class-name: com.mysql.cj.jdbc.Driver

  docker:
    compose:
      enabled: false

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:okrm@2025}

logging:
  file:
    path: /Users/chenbitao/.okrm/logs/user-service
  level:
    root: INFO
    org:
      springframework:
        orm:
          jpa: DEBUG
      hibernate: DEBUG
    com:
      useful_person:
        okrm: DEBUG
