# spring:
#   cloud:
#     nacos:
#       discovery:
#         server-addr: localhost:8848
#   datasource:
#       url: jdbc:mysql://localhost:3306/user_db?useSSL=false
#       username: root
#       password: Cbt03.15_
#       driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#       hibernate:
#         ddl-auto: update
#   redis:
#     host: localhost
#     port: 6379
#     password: yourpassword
#     cluster:
#       nodes:
#         - localhost:7001
#         - localhost:7002