server:
  port: 7001

spring:
  application:
    name: nacos-config
  config:
    import:
      - nacos:okrm-gateway.yml?refreshEnabled=true&group=DEFAULT_GROUP
  cloud:
    nacos:
      serverAddr: "[::1]:8848"
      # 以下配置项必须填写
      username: "nacos"
      password: "nacos"

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com.alibaba.cloud.nacos.configdata: debug
